#include "WindowControlDefinitions.h"

#include "ControlIds.h"

#include <algorithm>
#include <commctrl.h>

namespace {

constexpr DWORD kChildStyle = WS_CHILD | WS_VISIBLE;
constexpr DWORD kStaticStyle = kChildStyle;
constexpr DWORD kButtonStyle = kChildStyle | BS_PUSHBUTTON;
constexpr DWORD kPanelHeaderStyle = kChildStyle | BS_OWNERDRAW;
constexpr DWORD kEditStyle = kChildStyle | WS_BORDER | ES_AUTOHSCROLL;
constexpr DWORD kNumberEditStyle = kChildStyle | WS_BORDER | ES_NUMBER | ES_AUTOHSCROLL;
constexpr DWORD kComboStyle = kChildStyle | WS_TABSTOP | CBS_DROPDOWNLIST | WS_VSCROLL;
constexpr DWORD kCheckboxStyle = kChildStyle | WS_TABSTOP | BS_AUTOCHECKBOX;
constexpr DWORD kListStyle = kChildStyle | WS_BORDER | WS_VSCROLL | LBS_NOINTEGRALHEIGHT;
constexpr DWORD kPanelScrollStyle = kChildStyle | SBS_VERT;
constexpr DWORD kTrackbarStyle = kChildStyle | TBS_HORZ | TBS_AUTOTICKS | TBS_BOTTOM | WS_TABSTOP;
constexpr DWORD kSmallStaticStyle = kChildStyle | SS_CENTER;

} // namespace

const std::vector<WindowControlDefinition>& WindowControlDefinitions::All()
{
    static const std::vector<WindowControlDefinition> definitions = {
        {kIdDeviceLabel, L"STATIC", L"Device", kStaticStyle},
        {kIdDeviceCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdRefreshDevices, L"BUTTON", L"Refresh", kButtonStyle},
        {kIdOpen, L"BUTTON", L"Open", kButtonStyle},
        {kIdStop, L"BUTTON", L"Stop", kButtonStyle},
        {kIdFitView, L"BUTTON", L"", kButtonStyle | BS_OWNERDRAW},
        {kIdExposureLabel, L"STATIC", L"Exposure", kStaticStyle},
        {kIdExposureEdit, L"EDIT", L"10", kEditStyle},
        {kIdExposureApply, L"BUTTON", L"Apply", kButtonStyle},
        {kIdObjectiveLabel, L"STATIC", L"Objective", kStaticStyle},
        {kIdObjectiveCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdObjectiveNameEdit, L"EDIT", nullptr, kEditStyle},
        {kIdAddObjective, L"BUTTON", L"Add Obj", kButtonStyle},
        {kIdRenameObjective, L"BUTTON", L"Rename", kButtonStyle},
        {kIdDeleteObjective, L"BUTTON", L"Delete", kButtonStyle},
        {kIdCalibrationLengthLabel, L"STATIC", L"Scale length", kStaticStyle},
        {kIdCalibrationLengthEdit, L"EDIT", L"100", kEditStyle},
        {kIdCalibrationUnitCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdCalibrationStatusLabel, L"STATIC", L"Current scale: uncalibrated", kStaticStyle},
        {kIdCalibrate, L"BUTTON", L"Calibrate", kButtonStyle},
        {kIdClearCalibration, L"BUTTON", L"Clear Calib", kButtonStyle},
        {kIdLengthTool, L"BUTTON", L"Length", kButtonStyle},
        {kIdAngleTool, L"BUTTON", L"Angle", kButtonStyle},
        {kIdRectangleAreaTool, L"BUTTON", L"Area", kButtonStyle},
        {kIdPolygonAreaTool, L"BUTTON", L"Poly Area", kButtonStyle},
        {kIdFinishPolygonArea, L"BUTTON", L"Finish Poly", kButtonStyle},
        {kIdDeleteMeasurement, L"BUTTON", L"Delete Selected", kButtonStyle},
        {kIdClearMeasurements, L"BUTTON", L"Clear", kButtonStyle},
        {kIdExportCsv, L"BUTTON", L"Export CSV", kButtonStyle},
        {kIdExportImage, L"BUTTON", L"Export Image", kButtonStyle},
        {kIdOpenImage, L"BUTTON", L"Open Image", kButtonStyle},
        {kIdToggleFunctionPanel, L"BUTTON", L"", kButtonStyle | BS_OWNERDRAW},
        {kIdTogglePanelDock, L"BUTTON", L"", kButtonStyle | BS_OWNERDRAW},
        {kIdSaveDiagnostics, L"BUTTON", L"Save Report", kButtonStyle},
        {kIdDesignReportTemplate, L"BUTTON", L"Design Template", kButtonStyle},
        {kIdLoadReportTemplate, L"BUTTON", L"Load Template", kButtonStyle},
        {kIdClearReportTemplate, L"BUTTON", L"Clear Template", kButtonStyle},
        {kIdReportTemplateStatus, L"STATIC", L"Template: default", kStaticStyle},
        {kIdOpenProject, L"BUTTON", L"Open Project", kButtonStyle},
        {kIdSaveProject, L"BUTTON", L"Save Project", kButtonStyle},
        {kIdCameraPanelCard, L"BUTTON", L"Camera", kPanelHeaderStyle},
        {kIdImagePanelCard, L"BUTTON", L"Image", kPanelHeaderStyle},
        {kIdFluorescencePanelCard, L"BUTTON", L"Fluorescence", kPanelHeaderStyle},
        {kIdProcessingPanelCard, L"BUTTON", L"Processing", kPanelHeaderStyle},
        {kIdMeasurementPanelCard, L"BUTTON", L"Measurement", kPanelHeaderStyle},
        {kIdProjectPanelCard, L"BUTTON", L"Project", kPanelHeaderStyle},
        {kIdHistogramPanelCard, L"BUTTON", L"Histogram", kPanelHeaderStyle},
        {kIdAutoExposure, L"BUTTON", L"Auto Exposure", kButtonStyle},
        {kIdCameraExposureLabel, L"STATIC", L"Exposure", kStaticStyle},
        {kIdCameraExposureEdit, L"EDIT", L"10", kEditStyle},
        {kIdCameraExposureApply, L"BUTTON", L"Apply", kButtonStyle},
        {kIdCameraGainLabel, L"STATIC", L"Gain", kStaticStyle},
        {kIdCameraGainEdit, L"EDIT", L"1.0", kEditStyle},
        {kIdCameraGainApply, L"BUTTON", L"Apply", kButtonStyle},
        {kIdWhiteBalance, L"BUTTON", L"White Balance", kButtonStyle},
        {kIdHistogramChannelLabel, L"STATIC", L"Channel", kStaticStyle},
        {kIdHistogramChannelCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdHistogramBrightnessLabel, L"STATIC", L"Brightness", kStaticStyle},
        {kIdHistogramBrightnessSlider, TRACKBAR_CLASS, nullptr, kTrackbarStyle},
        {kIdHistogramBrightnessValue, L"STATIC", L"0", kSmallStaticStyle},
        {kIdHistogramContrastLabel, L"STATIC", L"Contrast", kStaticStyle},
        {kIdHistogramContrastSlider, TRACKBAR_CLASS, nullptr, kTrackbarStyle},
        {kIdHistogramContrastValue, L"STATIC", L"0", kSmallStaticStyle},
        {kIdHistogramGammaLabel, L"STATIC", L"Gamma", kStaticStyle},
        {kIdHistogramGammaSlider, TRACKBAR_CLASS, nullptr, kTrackbarStyle},
        {kIdHistogramGammaValue, L"STATIC", L"1.0", kSmallStaticStyle},
        {kIdHistogramResetAdjust, L"BUTTON", L"Reset", kButtonStyle},
        {kIdHistogramWindowLevelLabel, L"STATIC", L"Window Level", kStaticStyle},
        {kIdHistogramWindowLevelSlider, TRACKBAR_CLASS, nullptr, kTrackbarStyle},
        {kIdHistogramWindowLevelValue, L"STATIC", L"128", kSmallStaticStyle},
        {kIdHistogramWindowWidthLabel, L"STATIC", L"Window Width", kStaticStyle},
        {kIdHistogramWindowWidthSlider, TRACKBAR_CLASS, nullptr, kTrackbarStyle},
        {kIdHistogramWindowWidthValue, L"STATIC", L"256", kSmallStaticStyle},
        {kIdPseudoColorLabel, L"STATIC", L"Pseudo color", kStaticStyle},
        {kIdPseudoColorCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdDyeLabel, L"STATIC", L"Dye", kStaticStyle},
        {kIdDyeCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdDyeNameLabel, L"STATIC", L"Name", kStaticStyle},
        {kIdDyeNameEdit, L"EDIT", nullptr, kEditStyle},
        {kIdDyeExcitationLabel, L"STATIC", L"Ex", kStaticStyle},
        {kIdDyeExcitationEdit, L"EDIT", nullptr, kEditStyle},
        {kIdDyeEmissionLabel, L"STATIC", L"Em", kStaticStyle},
        {kIdDyeEmissionEdit, L"EDIT", nullptr, kEditStyle},
        {kIdDyeRedLabel, L"STATIC", L"R", kStaticStyle},
        {kIdDyeRedEdit, L"EDIT", nullptr, kNumberEditStyle},
        {kIdDyeGreenLabel, L"STATIC", L"G", kStaticStyle},
        {kIdDyeGreenEdit, L"EDIT", nullptr, kNumberEditStyle},
        {kIdDyeBlueLabel, L"STATIC", L"B", kStaticStyle},
        {kIdDyeBlueEdit, L"EDIT", nullptr, kNumberEditStyle},
        {kIdSaveDye, L"BUTTON", L"Save Dye", kButtonStyle},
        {kIdDeleteDye, L"BUTTON", L"Delete Dye", kButtonStyle},
        {kIdAddChannel, L"BUTTON", L"Add Channel", kButtonStyle},
        {kIdFusionPreview, L"BUTTON", L"Fusion Preview", kCheckboxStyle},
        {kIdClearChannels, L"BUTTON", L"Clear Channels", kButtonStyle},
        {kIdChannelLabel, L"STATIC", L"Channels", kStaticStyle},
        {kIdChannelList, L"LISTBOX", nullptr, kListStyle},
        {kIdChannelVisible, L"BUTTON", L"Visible", kCheckboxStyle},
        {kIdChannelBlackLabel, L"STATIC", L"Black", kStaticStyle},
        {kIdChannelBlackEdit, L"EDIT", L"0", kNumberEditStyle},
        {kIdChannelWhiteLabel, L"STATIC", L"White", kStaticStyle},
        {kIdChannelWhiteEdit, L"EDIT", L"255", kNumberEditStyle},
        {kIdApplyChannel, L"BUTTON", L"Apply Channel", kButtonStyle},
        {kIdStitchLiveSectionLabel, L"STATIC", L"Live capture", kStaticStyle},
        {kIdStitchImportSectionLabel, L"STATIC", L"Import images", kStaticStyle},
        {kIdStitchGallerySectionLabel, L"STATIC", L"Tile gallery", kStaticStyle},
        {kIdStitchSettingsSectionLabel, L"STATIC", L"Stitch settings", kStaticStyle},
        {kIdStitchOutputSectionLabel, L"STATIC", L"Output", kStaticStyle},
        {kIdEdfSectionLabel, L"STATIC", L"EDF", kStaticStyle},
        {kIdStitchModeLabel, L"STATIC", L"Layout", kStaticStyle},
        {kIdStitchModeCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdStitchSourceLabel, L"STATIC", L"Source", kStaticStyle},
        {kIdSelectStitchDirectory, L"BUTTON", L"Add Folder", kButtonStyle},
        {kIdSelectStitchFiles, L"BUTTON", L"Add Images", kButtonStyle},
        {kIdStitchSourceStatus, L"STATIC", L"(no images selected)", kStaticStyle},
        {kIdStitchRowsLabel, L"STATIC", L"Rows", kStaticStyle},
        {kIdStitchRowsEdit, L"EDIT", L"3", kNumberEditStyle},
        {kIdStitchColsLabel, L"STATIC", L"Columns", kStaticStyle},
        {kIdStitchColsEdit, L"EDIT", L"4", kNumberEditStyle},
        {kIdStitchMethodLabel, L"STATIC", L"Registration method", kStaticStyle},
        {kIdStitchMethodCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdStitchTransformLabel, L"STATIC", L"Transform model", kStaticStyle},
        {kIdStitchTransformCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdStitchBlendLabel, L"STATIC", L"Blend", kStaticStyle},
        {kIdStitchBlendCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdStitchSearchLabel, L"STATIC", L"Overlap", kStaticStyle},
        {kIdStitchSearchEdit, L"EDIT", L"25", kNumberEditStyle},
        {kIdStitchOverlapSlider, TRACKBAR_CLASS, nullptr, kTrackbarStyle},
        {kIdStitchOverlapValue, L"STATIC", L"25%", kSmallStaticStyle},
        {kIdStitchOrbRegistration, L"BUTTON", L"Micro auto registration", kCheckboxStyle},
        {kIdAddStitchTile, L"BUTTON", L"Add Tile", kButtonStyle},
        {kIdLiveStitchIntervalLabel, L"STATIC", L"Interval ms", kStaticStyle},
        {kIdLiveStitchIntervalEdit, L"EDIT", L"1200", kNumberEditStyle},
        {kIdStartLiveStitch, L"BUTTON", L"Start Live", kButtonStyle},
        {kIdStopLiveStitch, L"BUTTON", L"Stop Live", kButtonStyle},
        {kIdBuildStitch, L"BUTTON", L"Stitch Now", kButtonStyle},
        {kIdSaveStitchResult, L"BUTTON", L"Save Result", kButtonStyle},
        {kIdStitchTileLabel, L"STATIC", L"Tiles", kStaticStyle},
        {kIdStitchTileList, L"LISTBOX", nullptr, kListStyle},
        {kIdDeleteStitchTile, L"BUTTON", L"Delete Tile", kButtonStyle},
        {kIdClearStitchTiles, L"BUTTON", L"Clear Tiles", kButtonStyle},
        {kIdEdfRadiusLabel, L"STATIC", L"EDF radius", kStaticStyle},
        {kIdEdfRadiusEdit, L"EDIT", L"1", kNumberEditStyle},
        {kIdAddEdfFrame, L"BUTTON", L"Add EDF", kButtonStyle},
        {kIdBuildEdf, L"BUTTON", L"EDF", kButtonStyle},
        {kIdShowEdfComposite, L"BUTTON", L"EDF Image", kButtonStyle},
        {kIdShowEdfFocusMap, L"BUTTON", L"Focus Map", kButtonStyle},
        {kIdRetryProcessing, L"BUTTON", L"Retry", kButtonStyle},
        {kIdClearProcessing, L"BUTTON", L"Clear Processing", kButtonStyle},
        {kIdMeasurementNameEdit, L"EDIT", nullptr, kEditStyle},
        {kIdRenameMeasurement, L"BUTTON", L"Rename", kButtonStyle},
        {kIdResultsLabel, L"STATIC", L"Measurements", kStaticStyle},
        {kIdResultsList, L"LISTBOX", nullptr, kListStyle},
        {kIdPanelScrollBar, L"SCROLLBAR", nullptr, kPanelScrollStyle},
        {kIdAiPanelCard, L"BUTTON", L"AI", kPanelHeaderStyle},
        {kIdAiTaskTypeCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdAiModelArchitectureLabel, L"STATIC", L"Architecture", kStaticStyle},
        {kIdAiYoloInputSizeCombo, L"COMBOBOX", nullptr, kComboStyle},
        {kIdAiYoloAdvancedSectionLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiYoloNumAnchorsLabel, L"STATIC", L"Anchors", kStaticStyle},
        {kIdAiYoloNumAnchorsEdit, L"EDIT", L"3", kNumberEditStyle},
        {kIdAiYoloObjThresholdLabel, L"STATIC", L"Obj Thresh", kStaticStyle},
        {kIdAiYoloObjThresholdEdit, L"EDIT", L"0.5", kEditStyle},
        {kIdAiYoloNmsThresholdLabel, L"STATIC", L"NMS Thresh", kStaticStyle},
        {kIdAiYoloNmsThresholdEdit, L"EDIT", L"0.45", kEditStyle},
        {kIdAiYoloLearningRateLabel, L"STATIC", L"Learn Rate", kStaticStyle},
        {kIdAiYoloLearningRateEdit, L"EDIT", L"0.001", kEditStyle},
        {kIdAiYoloBatchSizeLabel, L"STATIC", L"Batch", kStaticStyle},
        {kIdAiYoloBatchSizeEdit, L"EDIT", L"8", kNumberEditStyle},
        {kIdAiCreateModel, L"BUTTON", L"Create YOLO Model", kButtonStyle},
        {kIdAiModelNameEdit, L"EDIT", nullptr, kEditStyle},
        {kIdAiLabelNameEdit, L"EDIT", nullptr, kEditStyle},
        {kIdAiLabelList, L"LISTBOX", nullptr, kListStyle},
        {kIdAiAddLabel, L"BUTTON", L"Add Label", kButtonStyle},
        {kIdAiDeleteLabel, L"BUTTON", L"Delete", kButtonStyle},
        {kIdAiCaptureSample, L"BUTTON", L"Capture Sample", kButtonStyle},
        {kIdAiSampleCountLabel, L"STATIC", L"Samples: 0", kStaticStyle},
        {kIdAiTrainModel, L"BUTTON", L"Train Model", kButtonStyle},
        {kIdAiTrainingProgress, L"STATIC", L"", kStaticStyle},
        {kIdAiTrainingLossLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiModelList, L"LISTBOX", nullptr, kListStyle},
        {kIdAiLoadModel, L"BUTTON", L"Load", kButtonStyle},
        {kIdAiSaveModel, L"BUTTON", L"Save Model", kButtonStyle},
        {kIdAiDeleteModel, L"BUTTON", L"Delete", kButtonStyle},
        {kIdAiRunInference, L"BUTTON", L"Run Inference", kButtonStyle},
        {kIdAiResultLabel, L"STATIC", L"Results", kStaticStyle},
        {kIdAiResultList, L"LISTBOX", nullptr, kListStyle},
        {kIdAiShowBoxes, L"BUTTON", L"Show Boxes", kCheckboxStyle},
        {kIdAiShowSegOverlay, L"BUTTON", L"Seg. Overlay", kCheckboxStyle},
        {kIdAiClearResults, L"BUTTON", L"Clear", kButtonStyle},
        {kIdAiClearSamples, L"BUTTON", L"Clear Samples", kButtonStyle},
        {kIdAiDatasetSectionLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiDatasetPathEdit, L"EDIT", nullptr, kEditStyle},
        {kIdAiImportDataset, L"BUTTON", L"Import Dataset", kButtonStyle},
        {kIdAiDatasetStatusLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiTrainingStatusLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiTrainingSectionLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiModelCenterSectionLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiModelVersionList, L"LISTBOX", nullptr, kListStyle},
        {kIdAiModelAccuracyLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiDeployStatusLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiDeployVersion, L"BUTTON", L"Deploy", kButtonStyle},
        {kIdAiInferenceSectionLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiInferenceTimeLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiConfThresholdLabel, L"STATIC", L"Conf", kStaticStyle},
        {kIdAiConfThresholdEdit, L"EDIT", L"0.5", kEditStyle},
        {kIdAiTrainingEpochsLabel, L"STATIC", L"Epochs", kStaticStyle},
        {kIdAiTrainingEpochsEdit, L"EDIT", L"30", kNumberEditStyle},
        {kIdAiValidationSplitLabel, L"STATIC", L"Val Split", kStaticStyle},
        {kIdAiValidationSplitEdit, L"EDIT", L"0.2", kEditStyle},
        {kIdAiTrainConfigSectionLabel, L"STATIC", L"", kStaticStyle},
        {kIdAiEvaluateModel, L"BUTTON", L"Evaluate", kButtonStyle},
    };
    return definitions;
}

const WindowControlDefinition* WindowControlDefinitions::Find(int control_id)
{
    const std::vector<WindowControlDefinition>& definitions = All();
    const auto found = std::find_if(
        definitions.begin(),
        definitions.end(),
        [&](const WindowControlDefinition& definition) {
            return definition.control_id == control_id;
        });
    return found == definitions.end() ? nullptr : &*found;
}
